version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.1.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - aws-cli/setup
      - checkout
      - run:
          name: install yarn
          command: npm install -g yarn
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy Front-End
          command: |
            npm run frontend:deploy
